linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  goimports:
    local-prefixes: choosy-backend

issues:
  exclude-dirs:
    - vendor
  exclude-generated: strict

run:
  timeout: 5m

