version: "2"
linters:
  enable:
    - misspell
    - unconvert
    - unparam
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - choosy-backend
  exclusions:
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
