name: helios

services:
  db:
    image: mysql:8.0
    container_name: helios-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-helios}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-helios}
    volumes:
      - helios_mysql_data:/var/lib/mysql
      - helios_mysql_logs:/var/log/mysql
      - ./hermes/sql/schema.sql:/docker-entrypoint-initdb.d/01-hermes-schema.sql:ro
      - ./hermes/sql/init.sql:/docker-entrypoint-initdb.d/02-hermes-init.sql:ro
      - ./zwei/sql/schema.sql:/docker-entrypoint-initdb.d/03-zwei-schema.sql:ro
      - ./chaos/sql/schema.sql:/docker-entrypoint-initdb.d/04-chaos-schema.sql:ro
      - ./environments/db/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 450m
          cpus: "1.5"

  cache:
    image: redis:7-alpine
    container_name: helios-cache
    ports:
      - "6379:6379"
    volumes:
      - helios_redis_data:/data
      - ./environments/cache/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"

volumes:
  helios_redis_data:
  helios_mysql_data:
  helios_mysql_logs:
