// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/heliannuuthus/helios/internal/aegis"
	"github.com/heliannuuthus/helios/internal/config"
	"github.com/heliannuuthus/helios/internal/database"
	"github.com/heliannuuthus/helios/internal/hermes"
	"github.com/heliannuuthus/helios/internal/hermes/upload"
	"github.com/heliannuuthus/helios/internal/iris"
	middleware2 "github.com/heliannuuthus/helios/internal/middleware"
	"github.com/heliannuuthus/helios/internal/zwei/favorite"
	"github.com/heliannuuthus/helios/internal/zwei/history"
	"github.com/heliannuuthus/helios/internal/zwei/home"
	"github.com/heliannuuthus/helios/internal/zwei/preference"
	"github.com/heliannuuthus/helios/internal/zwei/recipe"
	"github.com/heliannuuthus/helios/internal/zwei/recommend"
	"github.com/heliannuuthus/helios/internal/zwei/tag"
	"github.com/heliannuuthus/helios/pkg/aegis/middleware"
)

import (
	_ "github.com/heliannuuthus/helios/docs"
)

// Injectors from wire.go:

// InitializeApp 初始化应用（由 wire 生成）
func InitializeApp() (*App, error) {
	handler := provideRecipeHandler()
	service := provideHermesService()
	aegisHandler, err := provideAegisHandler(service)
	if err != nil {
		return nil, err
	}
	irisHandler := provideIrisHandler()
	favoriteHandler := provideFavoriteHandler()
	historyHandler := provideHistoryHandler()
	homeHandler := provideHomeHandler()
	tagHandler := provideTagHandler()
	recommendHandler := provideRecommendHandler()
	uploadHandler := provideUploadHandler()
	preferenceHandler := providePreferenceHandler()
	hermesHandler := provideHermesHandler(service)
	ginFactory, err := provideGinMiddlewareFactory()
	if err != nil {
		return nil, err
	}
	app := &App{
		RecipeHandler:     handler,
		AegisHandler:      aegisHandler,
		IrisHandler:       irisHandler,
		FavoriteHandler:   favoriteHandler,
		HistoryHandler:    historyHandler,
		HomeHandler:       homeHandler,
		TagHandler:        tagHandler,
		RecommendHandler:  recommendHandler,
		UploadHandler:     uploadHandler,
		PreferenceHandler: preferenceHandler,
		HermesHandler:     hermesHandler,
		MiddlewareFactory: ginFactory,
	}
	return app, nil
}

// wire.go:

// 业务模块 Handler（使用 Zwei 数据库）
func provideRecipeHandler() *recipe.Handler {
	return recipe.NewHandler(database.GetZwei())
}

func provideFavoriteHandler() *favorite.Handler {
	return favorite.NewHandler(database.GetZwei())
}

func provideHistoryHandler() *history.Handler {
	return history.NewHandler(database.GetZwei())
}

func providePreferenceHandler() *preference.Handler {
	return preference.NewHandler(database.GetZwei())
}

func provideTagHandler() *tag.Handler {
	return tag.NewHandler(database.GetZwei())
}

func provideRecommendHandler() *recommend.Handler {
	return recommend.NewHandler(database.GetZwei())
}

func provideHomeHandler() *home.Handler {
	return home.NewHandler(database.GetZwei())
}

// Hermes Service（供 aegis 模块复用）
func provideHermesService() *hermes.Service {
	return hermes.NewService()
}

// 认证模块 Handler（使用 Hermes 数据库，依赖 hermes.Service）
func provideAegisHandler(hermesService *hermes.Service) (*aegis.Handler, error) {
	db := database.GetHermes()
	userSvc := hermes.NewUserService(db)
	return aegis.Initialize(&aegis.InitConfig{
		HermesSvc: hermesService,
		UserSvc:   userSvc,
	})
}

func provideUploadHandler() *upload.Handler {
	return upload.NewHandler(database.GetHermes())
}

func provideHermesHandler(hermesService *hermes.Service) *hermes.Handler {
	return hermes.NewHandler(hermesService)
}

// Iris 用户信息模块 Handler
func provideIrisHandler() *iris.Handler {
	db := database.GetHermes()
	userSvc := hermes.NewUserService(db)
	credentialSvc := hermes.NewCredentialService(db)
	return iris.NewHandler(userSvc, credentialSvc)
}

// provideGinMiddlewareFactory 创建 Gin 中间件工厂
func provideGinMiddlewareFactory() (*middleware.GinFactory, error) {
	endpoint := config.GetAegisIssuer()
	encryptKeyProvider, err := middleware2.NewHermesKeyProvider()
	if err != nil {
		return nil, err
	}
	return middleware.NewGinFactory(context.Background(), endpoint, encryptKeyProvider)
}

// ProviderSet 提供者集合
var ProviderSet = wire.NewSet(recipe.NewService, favorite.NewService, history.NewService, preference.NewService, tag.NewService, recommend.NewService, provideRecipeHandler,
	provideFavoriteHandler,
	provideHistoryHandler,
	providePreferenceHandler,
	provideTagHandler,
	provideRecommendHandler,
	provideHomeHandler,

	provideHermesService,
	provideHermesHandler,

	provideAegisHandler,
	provideUploadHandler,

	provideIrisHandler,

	provideGinMiddlewareFactory,
)

// App 应用依赖容器
type App struct {
	RecipeHandler     *recipe.Handler
	AegisHandler      *aegis.Handler
	IrisHandler       *iris.Handler
	FavoriteHandler   *favorite.Handler
	HistoryHandler    *history.Handler
	HomeHandler       *home.Handler
	TagHandler        *tag.Handler
	RecommendHandler  *recommend.Handler
	UploadHandler     *upload.Handler
	PreferenceHandler *preference.Handler
	HermesHandler     *hermes.Handler
	MiddlewareFactory *middleware.GinFactory
}
