// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/heliannuuthus/helios/aegis"
	"github.com/heliannuuthus/helios/aegis/adapter"
	"github.com/heliannuuthus/helios/chaos"
	"github.com/heliannuuthus/helios/hermes"
	config2 "github.com/heliannuuthus/helios/hermes/config"
	"github.com/heliannuuthus/helios/iris"
	"github.com/heliannuuthus/helios/zwei"
	"github.com/heliannuuthus/helios/zwei/config"
)

import (
	_ "github.com/heliannuuthus/helios/docs"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	zwei := provideZwei()
	service := provideHermesService()
	handler, err := provideAegisHandler(service)
	if err != nil {
		return nil, err
	}
	hermesHandler := provideHermesHandler(service)
	chaosHandler, err := provideChaosHandler()
	if err != nil {
		return nil, err
	}
	app := &App{
		Zwei:          zwei,
		AegisHandler:  handler,
		HermesHandler: hermesHandler,
		ChaosHandler:  chaosHandler,
	}
	return app, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	provideZwei,
	provideHermesService,
	provideHermesHandler,
	provideAegisHandler,
	provideChaosHandler,
)

type App struct {
	Zwei          *zwei.Zwei
	AegisHandler  *aegis.Handler
	HermesHandler *hermes.Handler
	ChaosHandler  *chaos.Handler
}

func provideZwei() *zwei.Zwei {
	return zwei.New(config.InitDB())
}

func provideHermesService() *hermes.Service {
	return hermes.NewService(config2.InitDB())
}

func provideAegisHandler(hermesService *hermes.Service) (*aegis.Handler, error) {
	hermesAdapter := adapter.NewHermesAdapter(hermesService)
	userAdapter := adapter.NewUserAdapter(hermesService)
	credentialStore := adapter.NewCredentialStoreAdapter(hermesService)
	credentialSvc := iris.NewCredentialService(credentialStore)
	return aegis.Initialize(hermesAdapter, userAdapter, credentialSvc)
}

func provideHermesHandler(hermesService *hermes.Service) *hermes.Handler {
	return hermes.NewHandler(hermesService)
}

func provideChaosHandler() (*chaos.Handler, error) {
	db := config2.InitDB()
	chaosModule, err := chaos.New(db)
	if err != nil {
		return nil, err
	}
	return chaosModule.Handler(), nil
}
