// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"choosy-backend/internal/auth"
	"choosy-backend/internal/database"
	"choosy-backend/internal/favorite"
	"choosy-backend/internal/handlers"
	"choosy-backend/internal/history"
	"choosy-backend/internal/preference"
	"choosy-backend/internal/recipe"
	"choosy-backend/internal/recommend"
	"choosy-backend/internal/tag"
	"github.com/google/wire"
	"gorm.io/gorm"
)

import (
	_ "choosy-backend/docs"
)

// Injectors from wire.go:

// InitializeApp 初始化应用（由 wire 生成）
func InitializeApp() (*App, error) {
	db := database.Get()
	recipeHandler := handlers.NewRecipeHandler(db)
	authHandler := handlers.NewAuthHandler(db)
	favoriteHandler := handlers.NewFavoriteHandler(db)
	historyHandler := handlers.NewHistoryHandler(db)
	homeHandler := handlers.NewHomeHandler(db)
	tagHandler := handlers.NewTagHandler(db)
	recommendHandler := handlers.NewRecommendHandler(db)
	uploadHandler := handlers.NewUploadHandler(db)
	preferenceHandler := handlers.NewPreferenceHandler(db)
	app := &App{
		DB:                db,
		RecipeHandler:     recipeHandler,
		AuthHandler:       authHandler,
		FavoriteHandler:   favoriteHandler,
		HistoryHandler:    historyHandler,
		HomeHandler:       homeHandler,
		TagHandler:        tagHandler,
		RecommendHandler:  recommendHandler,
		UploadHandler:     uploadHandler,
		PreferenceHandler: preferenceHandler,
	}
	return app, nil
}

// wire.go:

// ProviderSet 提供者集合
var ProviderSet = wire.NewSet(database.Get, recipe.NewService, auth.NewService, favorite.NewService, history.NewService, preference.NewService, tag.NewService, recommend.NewService, handlers.NewRecipeHandler, handlers.NewAuthHandler, handlers.NewFavoriteHandler, handlers.NewHistoryHandler, handlers.NewHomeHandler, handlers.NewTagHandler, handlers.NewRecommendHandler, handlers.NewUploadHandler, handlers.NewPreferenceHandler)

// App 应用依赖容器
type App struct {
	DB                *gorm.DB
	RecipeHandler     *handlers.RecipeHandler
	AuthHandler       *handlers.AuthHandler
	FavoriteHandler   *handlers.FavoriteHandler
	HistoryHandler    *handlers.HistoryHandler
	HomeHandler       *handlers.HomeHandler
	TagHandler        *handlers.TagHandler
	RecommendHandler  *handlers.RecommendHandler
	UploadHandler     *handlers.UploadHandler
	PreferenceHandler *handlers.PreferenceHandler
}
