// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/context": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据经纬度获取位置、天气、时间信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "context"
                ],
                "summary": "获取推荐上下文",
                "parameters": [
                    {
                        "description": "上下文请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ContextRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ContextResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/favorites": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "获取收藏列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分类筛选",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.FavoriteListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "添加收藏",
                "parameters": [
                    {
                        "description": "收藏信息",
                        "name": "favorite",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.FavoriteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.FavoriteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/favorites/batch-check": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "批量检查收藏状态",
                "parameters": [
                    {
                        "description": "菜谱ID列表",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BatchCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.BatchCheckResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/favorites/{recipe_id}": {
            "delete": {
                "tags": [
                    "favorites"
                ],
                "summary": "取消收藏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜谱ID",
                        "name": "recipe_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/favorites/{recipe_id}/check": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "检查是否已收藏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜谱ID",
                        "name": "recipe_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CheckFavoriteResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "获取浏览历史列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分类筛选",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HistoryListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "添加浏览记录",
                "parameters": [
                    {
                        "description": "浏览记录信息",
                        "name": "history",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.HistoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.HistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "history"
                ],
                "summary": "清空浏览历史",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/history/{recipe_id}": {
            "delete": {
                "tags": [
                    "history"
                ],
                "summary": "删除浏览记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜谱ID",
                        "name": "recipe_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/home/banners": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "home"
                ],
                "summary": "获取首页 Banner",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.BannerItem"
                            }
                        }
                    }
                }
            }
        },
        "/api/home/hot": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "home"
                ],
                "summary": "获取热门菜谱（按收藏数排序）",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 6,
                        "description": "数量限制",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.RecipeListItem"
                            }
                        }
                    }
                }
            }
        },
        "/api/home/recommend": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "home"
                ],
                "summary": "获取推荐菜谱（随机）",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 4,
                        "description": "数量限制",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.RecipeListItem"
                            }
                        }
                    }
                }
            }
        },
        "/api/profile": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserProfile"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "更新当前用户信息",
                "parameters": [
                    {
                        "description": "更新请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/recipes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "获取菜谱列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分类",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.RecipeListItem"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "创建新菜谱",
                "parameters": [
                    {
                        "description": "菜谱信息",
                        "name": "recipe",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RecipeCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.RecipeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/recipes/batch": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "批量创建菜谱",
                "parameters": [
                    {
                        "description": "菜谱列表",
                        "name": "recipes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.RecipeCreateRequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.RecipeResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/recipes/categories/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "获取所有分类",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.CategoryResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/recipes/{recipe_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "获取菜谱详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜谱ID",
                        "name": "recipe_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.RecipeResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "更新菜谱",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜谱ID",
                        "name": "recipe_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "recipe",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RecipeUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.RecipeResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "recipes"
                ],
                "summary": "删除菜谱",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜谱ID",
                        "name": "recipe_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/recommend": {
            "post": {
                "description": "根据地理位置、天气、时间等因素智能推荐菜谱（基于 LLM，支持用户个性化）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recommend"
                ],
                "summary": "获取智能推荐菜谱",
                "parameters": [
                    {
                        "description": "推荐请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RecommendRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "default": 6,
                        "description": "返回数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.RecommendResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/revoke": {
            "post": {
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "撤销 token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "要撤销的 refresh_token",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.OAuth2Error"
                        }
                    }
                }
            }
        },
        "/api/revoke-all": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "登出所有设备",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/stats": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取当前用户的收藏数和浏览历史数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "获取用户统计数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.StatsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tags/cuisines": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "获取所有菜系",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.TagValueResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/tags/flavors": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "获取所有口味",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.TagValueResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/tags/scenes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "获取所有场景",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.TagValueResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/token": {
            "post": {
                "description": "支持 authorization_code（微信登录）和 refresh_token 两种 grant_type",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "获取/刷新 token",
                "parameters": [
                    {
                        "enum": [
                            "authorization_code",
                            "refresh_token"
                        ],
                        "type": "string",
                        "description": "授权类型",
                        "name": "grant_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "微信登录 code（grant_type=authorization_code 时必填）",
                        "name": "code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "刷新令牌（grant_type=refresh_token 时必填）",
                        "name": "refresh_token",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.OAuth2Error"
                        }
                    },
                    "412": {
                        "description": "refresh_token 无效或已过期",
                        "schema": {
                            "$ref": "#/definitions/handlers.OAuth2Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.OAuth2Error"
                        }
                    }
                }
            }
        },
        "/api/upload/image": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upload"
                ],
                "summary": "上传图片到 OSS",
                "parameters": [
                    {
                        "type": "string",
                        "description": "完整的 OSS 对象键，如 avatars/user123.jpg（优先级高于 prefix）",
                        "name": "object-key",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "文件路径前缀，如 avatars, images（当 object-key 为空时使用）",
                        "name": "prefix",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UploadImageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.BannerItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "link_type": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "handlers.BatchCheckRequest": {
            "type": "object",
            "required": [
                "recipe_ids"
            ],
            "properties": {
                "recipe_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.BatchCheckResponse": {
            "type": "object",
            "properties": {
                "favorited_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.CategoryResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "handlers.CheckFavoriteResponse": {
            "type": "object",
            "properties": {
                "is_favorite": {
                    "type": "boolean"
                }
            }
        },
        "handlers.ContextRequest": {
            "type": "object",
            "required": [
                "latitude",
                "longitude"
            ],
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "handlers.ContextResponse": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/handlers.LocationInfo"
                },
                "time": {
                    "$ref": "#/definitions/handlers.TimeInfo"
                },
                "weather": {
                    "$ref": "#/definitions/handlers.WeatherInfo"
                }
            }
        },
        "handlers.FavoriteListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "recipe": {
                    "$ref": "#/definitions/handlers.RecipeListItem"
                },
                "recipe_id": {
                    "type": "string"
                }
            }
        },
        "handlers.FavoriteListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.FavoriteListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handlers.FavoriteRequest": {
            "type": "object",
            "required": [
                "recipe_id"
            ],
            "properties": {
                "recipe_id": {
                    "type": "string"
                }
            }
        },
        "handlers.FavoriteResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "recipe_id": {
                    "type": "string"
                }
            }
        },
        "handlers.HistoryListItem": {
            "type": "object",
            "properties": {
                "recipe": {
                    "$ref": "#/definitions/handlers.RecipeListItem"
                },
                "recipe_id": {
                    "type": "string"
                },
                "viewed_at": {
                    "type": "string"
                }
            }
        },
        "handlers.HistoryListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.HistoryListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handlers.HistoryRequest": {
            "type": "object",
            "required": [
                "recipe_id"
            ],
            "properties": {
                "recipe_id": {
                    "type": "string"
                }
            }
        },
        "handlers.HistoryResponse": {
            "type": "object",
            "properties": {
                "recipe_id": {
                    "type": "string"
                },
                "viewed_at": {
                    "type": "string"
                }
            }
        },
        "handlers.IngredientRequest": {
            "type": "object",
            "required": [
                "name",
                "text_quantity"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "text_quantity": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "handlers.IngredientResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "text_quantity": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "handlers.LocationInfo": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                }
            }
        },
        "handlers.OAuth2Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "error_description": {
                    "type": "string"
                }
            }
        },
        "handlers.RecipeCreateRequest": {
            "type": "object",
            "required": [
                "category",
                "difficulty",
                "name",
                "servings"
            ],
            "properties": {
                "additional_notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "category": {
                    "type": "string"
                },
                "cook_time_minutes": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.IngredientRequest"
                    }
                },
                "name": {
                    "type": "string"
                },
                "prep_time_minutes": {
                    "type": "integer"
                },
                "servings": {
                    "type": "integer"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.StepRequest"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_time_minutes": {
                    "type": "integer"
                }
            }
        },
        "handlers.RecipeListItem": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/handlers.TagsGrouped"
                },
                "total_time_minutes": {
                    "type": "integer"
                }
            }
        },
        "handlers.RecipeResponse": {
            "type": "object",
            "properties": {
                "additional_notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "category": {
                    "type": "string"
                },
                "cook_time_minutes": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.IngredientResponse"
                    }
                },
                "name": {
                    "type": "string"
                },
                "prep_time_minutes": {
                    "type": "integer"
                },
                "servings": {
                    "type": "integer"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.StepResponse"
                    }
                },
                "tags": {
                    "$ref": "#/definitions/handlers.TagsGrouped"
                },
                "total_time_minutes": {
                    "type": "integer"
                }
            }
        },
        "handlers.RecipeUpdateRequest": {
            "type": "object",
            "properties": {
                "additional_notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "category": {
                    "type": "string"
                },
                "cook_time_minutes": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.IngredientRequest"
                    }
                },
                "name": {
                    "type": "string"
                },
                "prep_time_minutes": {
                    "type": "integer"
                },
                "servings": {
                    "type": "integer"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.StepRequest"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_time_minutes": {
                    "type": "integer"
                }
            }
        },
        "handlers.RecommendRecipeItem": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "reason": {
                    "description": "该菜品的推荐理由",
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/handlers.TagsGrouped"
                },
                "total_time_minutes": {
                    "type": "integer"
                }
            }
        },
        "handlers.RecommendRequest": {
            "type": "object",
            "required": [
                "latitude",
                "longitude"
            ],
            "properties": {
                "exclude_ids": {
                    "description": "排除的菜谱 ID（换一批时传入已推荐的）",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "handlers.RecommendResponse": {
            "type": "object",
            "properties": {
                "recipes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.RecommendRecipeItem"
                    }
                },
                "remaining": {
                    "description": "今日剩余推荐次数",
                    "type": "integer"
                },
                "summary": {
                    "description": "LLM 生成的一句话整体评价",
                    "type": "string"
                }
            }
        },
        "handlers.StatsResponse": {
            "type": "object",
            "properties": {
                "favorites": {
                    "description": "收藏数",
                    "type": "integer"
                },
                "history": {
                    "description": "浏览历史数",
                    "type": "integer"
                }
            }
        },
        "handlers.StepRequest": {
            "type": "object",
            "required": [
                "description",
                "step"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "step": {
                    "type": "integer"
                }
            }
        },
        "handlers.StepResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "step": {
                    "type": "integer"
                }
            }
        },
        "handlers.TagValueResponse": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "handlers.TagsGrouped": {
            "type": "object",
            "properties": {
                "cuisines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "flavors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scenes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.TimeInfo": {
            "type": "object",
            "properties": {
                "day_of_week": {
                    "type": "integer"
                },
                "hour": {
                    "type": "integer"
                },
                "meal_time": {
                    "type": "string"
                },
                "season": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "handlers.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "handlers.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "移除 url 验证，允许临时路径或 OSS URL",
                    "type": "string",
                    "maxLength": 512
                },
                "gender": {
                    "type": "integer",
                    "enum": [
                        0,
                        1,
                        2
                    ]
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 64
                },
                "phone_code": {
                    "description": "小程序授权码，用于绑定手机号；传空字符串表示解绑，不传则不处理",
                    "type": "string"
                }
            }
        },
        "handlers.UploadImageResponse": {
            "type": "object",
            "properties": {
                "url": {
                    "description": "上传后的图片 URL",
                    "type": "string"
                }
            }
        },
        "handlers.UserProfile": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "openid": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "handlers.WeatherInfo": {
            "type": "object",
            "properties": {
                "humidity": {
                    "type": "integer"
                },
                "icon": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                },
                "weather": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "输入 \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:18000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Choosy API",
	Description:      "菜谱管理系统后端 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
