// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/home/banners": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "home"
                ],
                "summary": "获取首页 Banner",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/home.BannerItem"
                            }
                        }
                    }
                }
            }
        },
        "/api/home/hot": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "home"
                ],
                "summary": "获取热门菜谱（按收藏数排序）",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 6,
                        "description": "数量限制",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/zwei.RecipeListItem"
                            }
                        }
                    }
                }
            }
        },
        "/api/home/recommend": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "home"
                ],
                "summary": "获取推荐菜谱（随机）",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 4,
                        "description": "数量限制",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/zwei.RecipeListItem"
                            }
                        }
                    }
                }
            }
        },
        "/api/preferences": {
            "get": {
                "description": "获取口味、忌口、过敏的所有可选选项（从缓存索引获取，性能最优）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "preference"
                ],
                "summary": "获取所有偏好选项",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/preference.OptionsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/recipes": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "获取菜谱列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分类",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/zwei.RecipeListItem"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "创建新菜谱",
                "parameters": [
                    {
                        "description": "菜谱信息",
                        "name": "recipe",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipe.RecipeCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/recipe.RecipeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/recipes/batch": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "批量创建菜谱",
                "parameters": [
                    {
                        "description": "菜谱列表",
                        "name": "recipes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/recipe.RecipeCreateRequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/recipe.RecipeResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/recipes/categories/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "获取所有分类",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/recipe.CategoryResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/recipes/{recipe_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "获取菜谱详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜谱ID",
                        "name": "recipe_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipe.RecipeResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "recipes"
                ],
                "summary": "删除菜谱",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜谱ID",
                        "name": "recipe_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recipes"
                ],
                "summary": "更新菜谱",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜谱ID",
                        "name": "recipe_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "recipe",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recipe.RecipeUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recipe.RecipeResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/recommend": {
            "post": {
                "description": "根据地理位置、天气、时间等因素智能推荐菜谱（基于 LLM，支持用户个性化）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recommend"
                ],
                "summary": "获取智能推荐菜谱",
                "parameters": [
                    {
                        "description": "推荐请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recommend.RecommendRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "default": 6,
                        "description": "返回数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recommend.RecommendResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/recommend/context": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据经纬度获取位置、天气、时间信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recommend"
                ],
                "summary": "获取推荐上下文",
                "parameters": [
                    {
                        "description": "上下文请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/recommend.ContextRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/recommend.ContextResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tags": {
            "get": {
                "description": "获取标签列表，支持通过查询参数过滤。所有类型（cuisine/flavor/scene/taboo/allergy）都统一使用此接口",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "获取标签列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "标签类型: cuisine/flavor/scene/taboo/allergy",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "菜谱ID（获取特定菜谱的标签，仅用于 cuisine/flavor/scene）",
                        "name": "recipe_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tag.TagValueResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "创建标签或选项。如果 recipe_id 为空，创建选项（仅支持 taboo/allergy）；如果 recipe_id 不为空，创建菜谱标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "创建标签",
                "parameters": [
                    {
                        "description": "标签信息",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tag.CreateTagRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/tag.TagValueResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/tags/{type}": {
            "get": {
                "description": "支持所有类型：cuisine/flavor/scene/taboo/allergy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "根据类型获取标签",
                "parameters": [
                    {
                        "type": "string",
                        "description": "标签类型: cuisine/flavor/scene/taboo/allergy",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/tag.TagValueResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/tags/{type}/{value}": {
            "put": {
                "description": "更新标签或选项的显示名称",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "更新标签",
                "parameters": [
                    {
                        "type": "string",
                        "description": "标签类型",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标签值",
                        "name": "value",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "菜谱ID（更新菜谱标签时必填，更新选项时留空）",
                        "name": "recipe_id",
                        "in": "query"
                    },
                    {
                        "description": "更新内容",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tag.UpdateTagRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tag.TagValueResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "删除标签或选项",
                "tags": [
                    "tags"
                ],
                "summary": "删除标签",
                "parameters": [
                    {
                        "type": "string",
                        "description": "标签类型",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标签值",
                        "name": "value",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "菜谱ID（删除菜谱标签时必填，删除选项时留空）",
                        "name": "recipe_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/favorites": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "获取收藏列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分类筛选",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/favorite.FavoriteListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "添加收藏",
                "parameters": [
                    {
                        "description": "收藏信息",
                        "name": "favorite",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/favorite.FavoriteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/favorite.FavoriteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/favorites/batch-check": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "批量检查收藏状态",
                "parameters": [
                    {
                        "description": "菜谱ID列表",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/favorite.BatchCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/favorite.BatchCheckResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/favorites/{recipe_id}": {
            "delete": {
                "tags": [
                    "favorites"
                ],
                "summary": "取消收藏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜谱ID",
                        "name": "recipe_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/favorites/{recipe_id}/check": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "favorites"
                ],
                "summary": "检查是否已收藏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜谱ID",
                        "name": "recipe_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/favorite.CheckFavoriteResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "获取浏览历史列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分类筛选",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "限制数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "偏移量",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/history.HistoryListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "history"
                ],
                "summary": "添加浏览记录",
                "parameters": [
                    {
                        "description": "浏览记录信息",
                        "name": "history",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/history.HistoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/history.HistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "history"
                ],
                "summary": "清空浏览历史",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/history/{recipe_id}": {
            "delete": {
                "tags": [
                    "history"
                ],
                "summary": "删除浏览记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "菜谱ID",
                        "name": "recipe_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/user/preference": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的偏好设置（包含选中状态）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "preference"
                ],
                "summary": "获取用户偏好",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/preference.UserPreferencesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新当前用户的偏好设置（全量替换）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "preference"
                ],
                "summary": "更新用户偏好",
                "parameters": [
                    {
                        "description": "偏好设置",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/preference.UpdatePreferencesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "favorite.BatchCheckRequest": {
            "type": "object",
            "required": [
                "recipe_ids"
            ],
            "properties": {
                "recipe_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "favorite.BatchCheckResponse": {
            "type": "object",
            "properties": {
                "favorited_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "favorite.CheckFavoriteResponse": {
            "type": "object",
            "properties": {
                "is_favorite": {
                    "type": "boolean"
                }
            }
        },
        "favorite.FavoriteListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "recipe": {
                    "$ref": "#/definitions/zwei.RecipeListItem"
                },
                "recipe_id": {
                    "type": "string"
                }
            }
        },
        "favorite.FavoriteListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/favorite.FavoriteListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "favorite.FavoriteRequest": {
            "type": "object",
            "required": [
                "recipe_id"
            ],
            "properties": {
                "recipe_id": {
                    "type": "string"
                }
            }
        },
        "favorite.FavoriteResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "recipe_id": {
                    "type": "string"
                }
            }
        },
        "history.HistoryListItem": {
            "type": "object",
            "properties": {
                "recipe": {
                    "$ref": "#/definitions/zwei.RecipeListItem"
                },
                "recipe_id": {
                    "type": "string"
                },
                "viewed_at": {
                    "type": "string"
                }
            }
        },
        "history.HistoryListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/history.HistoryListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "history.HistoryRequest": {
            "type": "object",
            "required": [
                "recipe_id"
            ],
            "properties": {
                "recipe_id": {
                    "type": "string"
                }
            }
        },
        "history.HistoryResponse": {
            "type": "object",
            "properties": {
                "recipe_id": {
                    "type": "string"
                },
                "viewed_at": {
                    "type": "string"
                }
            }
        },
        "home.BannerItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "link": {
                    "type": "string"
                },
                "link_type": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "patch.Optional-array_recipe_IngredientRequest": {
            "type": "object"
        },
        "patch.Optional-array_recipe_StepRequest": {
            "type": "object"
        },
        "patch.Optional-array_string": {
            "type": "object"
        },
        "patch.Optional-int": {
            "type": "object"
        },
        "patch.Optional-string": {
            "type": "object"
        },
        "preference.OptionItem": {
            "type": "object",
            "properties": {
                "label": {
                    "description": "显示名称",
                    "type": "string"
                },
                "value": {
                    "description": "标签值",
                    "type": "string"
                }
            }
        },
        "preference.OptionItemWithSelected": {
            "type": "object",
            "properties": {
                "label": {
                    "description": "显示名称",
                    "type": "string"
                },
                "selected": {
                    "description": "是否已选择",
                    "type": "boolean"
                },
                "value": {
                    "description": "标签值",
                    "type": "string"
                }
            }
        },
        "preference.OptionsResponse": {
            "type": "object",
            "properties": {
                "allergies": {
                    "description": "过敏选项",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/preference.OptionItem"
                    }
                },
                "flavors": {
                    "description": "口味选项",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/preference.OptionItem"
                    }
                },
                "taboos": {
                    "description": "忌口选项",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/preference.OptionItem"
                    }
                }
            }
        },
        "preference.UpdatePreferencesRequest": {
            "type": "object",
            "properties": {
                "allergies": {
                    "description": "过敏选项值列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "flavors": {
                    "description": "口味选项值列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "taboos": {
                    "description": "忌口选项值列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "preference.UserPreferencesResponse": {
            "type": "object",
            "properties": {
                "allergies": {
                    "description": "过敏偏好",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/preference.OptionItemWithSelected"
                    }
                },
                "flavors": {
                    "description": "口味偏好",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/preference.OptionItemWithSelected"
                    }
                },
                "taboos": {
                    "description": "忌口偏好",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/preference.OptionItemWithSelected"
                    }
                }
            }
        },
        "recipe.CategoryResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "recipe.IngredientRequest": {
            "type": "object",
            "required": [
                "name",
                "text_quantity"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "text_quantity": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "recipe.IngredientResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "text_quantity": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "recipe.RecipeCreateRequest": {
            "type": "object",
            "required": [
                "category",
                "difficulty",
                "name",
                "servings"
            ],
            "properties": {
                "additional_notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "category": {
                    "type": "string"
                },
                "cook_time_minutes": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recipe.IngredientRequest"
                    }
                },
                "name": {
                    "type": "string"
                },
                "prep_time_minutes": {
                    "type": "integer"
                },
                "servings": {
                    "type": "integer"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recipe.StepRequest"
                    }
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_time_minutes": {
                    "type": "integer"
                }
            }
        },
        "recipe.RecipeResponse": {
            "type": "object",
            "properties": {
                "additional_notes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "category": {
                    "type": "string"
                },
                "cook_time_minutes": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recipe.IngredientResponse"
                    }
                },
                "name": {
                    "type": "string"
                },
                "prep_time_minutes": {
                    "type": "integer"
                },
                "servings": {
                    "type": "integer"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recipe.StepResponse"
                    }
                },
                "tags": {
                    "$ref": "#/definitions/zwei.TagsGrouped"
                },
                "total_time_minutes": {
                    "type": "integer"
                }
            }
        },
        "recipe.RecipeUpdateRequest": {
            "type": "object",
            "properties": {
                "additional_notes": {
                    "$ref": "#/definitions/patch.Optional-array_string"
                },
                "category": {
                    "$ref": "#/definitions/patch.Optional-string"
                },
                "cook_time_minutes": {
                    "$ref": "#/definitions/patch.Optional-int"
                },
                "description": {
                    "$ref": "#/definitions/patch.Optional-string"
                },
                "difficulty": {
                    "$ref": "#/definitions/patch.Optional-int"
                },
                "images": {
                    "$ref": "#/definitions/patch.Optional-array_string"
                },
                "ingredients": {
                    "$ref": "#/definitions/patch.Optional-array_recipe_IngredientRequest"
                },
                "name": {
                    "$ref": "#/definitions/patch.Optional-string"
                },
                "prep_time_minutes": {
                    "$ref": "#/definitions/patch.Optional-int"
                },
                "servings": {
                    "$ref": "#/definitions/patch.Optional-int"
                },
                "steps": {
                    "$ref": "#/definitions/patch.Optional-array_recipe_StepRequest"
                },
                "tags": {
                    "$ref": "#/definitions/patch.Optional-array_string"
                },
                "total_time_minutes": {
                    "$ref": "#/definitions/patch.Optional-int"
                }
            }
        },
        "recipe.StepRequest": {
            "type": "object",
            "required": [
                "description",
                "step"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "step": {
                    "type": "integer"
                }
            }
        },
        "recipe.StepResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "step": {
                    "type": "integer"
                }
            }
        },
        "recommend.ContextRequest": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "recommend.ContextResponse": {
            "type": "object",
            "properties": {
                "location": {
                    "$ref": "#/definitions/recommend.LocationInfo"
                },
                "time": {
                    "$ref": "#/definitions/recommend.TimeInfo"
                },
                "weather": {
                    "$ref": "#/definitions/recommend.WeatherInfoResponse"
                }
            }
        },
        "recommend.LocationInfo": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                }
            }
        },
        "recommend.RecommendRecipeItem": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "reason": {
                    "description": "该菜品的推荐理由",
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/zwei.TagsGrouped"
                },
                "total_time_minutes": {
                    "type": "integer"
                }
            }
        },
        "recommend.RecommendRequest": {
            "type": "object",
            "required": [
                "latitude",
                "longitude"
            ],
            "properties": {
                "exclude_ids": {
                    "description": "排除的菜谱 ID（换一批时传入已推荐的）",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "recommend.RecommendResponse": {
            "type": "object",
            "properties": {
                "recipes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/recommend.RecommendRecipeItem"
                    }
                },
                "remaining": {
                    "description": "今日剩余推荐次数",
                    "type": "integer"
                },
                "summary": {
                    "description": "LLM 生成的一句话整体评价",
                    "type": "string"
                }
            }
        },
        "recommend.TimeInfo": {
            "type": "object",
            "properties": {
                "day_of_week": {
                    "type": "integer"
                },
                "hour": {
                    "type": "integer"
                },
                "meal_time": {
                    "type": "string"
                },
                "season": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "recommend.WeatherInfoResponse": {
            "type": "object",
            "properties": {
                "humidity": {
                    "type": "integer"
                },
                "icon": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                },
                "weather": {
                    "type": "string"
                }
            }
        },
        "tag.CreateTagRequest": {
            "type": "object",
            "required": [
                "label",
                "type",
                "value"
            ],
            "properties": {
                "label": {
                    "description": "显示名称",
                    "type": "string"
                },
                "recipe_id": {
                    "description": "菜谱ID（可选，为空时创建选项）",
                    "type": "string"
                },
                "type": {
                    "description": "标签类型",
                    "type": "string"
                },
                "value": {
                    "description": "标签值",
                    "type": "string"
                }
            }
        },
        "tag.TagValueResponse": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "tag.UpdateTagRequest": {
            "type": "object",
            "required": [
                "label"
            ],
            "properties": {
                "label": {
                    "type": "string"
                }
            }
        },
        "zwei.RecipeListItem": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/zwei.TagsGrouped"
                },
                "total_time_minutes": {
                    "type": "integer"
                }
            }
        },
        "zwei.TagsGrouped": {
            "type": "object",
            "properties": {
                "cuisines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "flavors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scenes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "输入 \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:18000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Helios API",
	Description:      "Helios 统一后端 API - 提供认证、业务和身份与访问管理服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
