name: Pipeline

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: heliannuuthus/hephaestus/.github/workflows/ci-golang-service.yml@main
    with:
      generate-commands: |
        go install github.com/google/wire/cmd/wire@latest
        go install github.com/swaggo/swag/cmd/swag@latest
        wire ./...
        swag init --parseDependency --parseInternal

  containerize:
    if: github.event_name == 'push'
    needs: [ci]
    uses: heliannuuthus/hephaestus/.github/workflows/ci-containerize.yml@main
    with:
      version: ${{ needs.ci.outputs.version }}
      targets: build/
    permissions:
      contents: read
      packages: write
